export const ADD_RESULT = 'ADD_RESULT';

export const FETCH_RESULT_REQUEST = 'FETCH_RESULT_REQUEST';
export const FETCH_RESULT_FAILURE = 'FETCH_RESULT_FAILURE';
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
